matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
        - CSC_IDENTITY_AUTO_DISCOVERY=false

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - npm run build
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  only:
    - master

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file: "test"
  skip_cleanup: true
  on:
    tags: false