matrix:
  include:
    - os: linux
      language: node_js
      node_js: "10"

script:
  - npm run dist

branches:
  only:
    - master

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file:
    - "dist/diploma-1.0.0.zip"
  skip_cleanup: true
  on:
    tags: false