export const ADD_FIGURE = 'ADD_FIGURE';
export const RENAME_FIGURE = 'RENAME_FIGURE';
export const DELETE_FIGURE = 'DELETE_FIGURE';
export const OPEN_FIGURE = 'OPEN_FIGURE';
export const SELECT_FEATURE = 'SELECT_FEATURE';
export const ONLY_IMPORTANT_FEATURES = 'ONLY_IMPORTANT_FEATURES';